const selectedIcons = [
    'openmoji:chart-increasing',
    'openmoji:code-editor',
    'noto:newspaper',
    'noto:books',
    'ic:outline-heat-pump',
    'noto:briefcase',
    'noto:satellite-antenna',
    'noto:satellite',
    'noto:airplane',
    'noto:rocket',
    'emojione:house-with-garden',
    'emojione:bust-in-silhouette',
    'emojione:gear',
    'emojione:page-facing-up',
    'emojione:bar-chart',
    'emojione:envelope',
    'emojione:bell',
    'emojione:file-folder',
    'emojione:card-file-box',
    'emojione:shield',
    'emojione:shopping-cart',
    'emojione:credit-card',
    'emojione:cloud',
    'emojione:locked',
    'emojione:star',
    'emojione:money-bag',
    'emojione:package',
    'emojione:memo',
    'emojione:clipboard',
    'emojione:round-pushpin',
    'emojione:bookmark-tabs',
    'emojione:world-map',
    'emojione:alarm-clock',
    'emojione:calendar',
    'emojione:mobile-phone',
    'emojione:desktop-computer',
    'emojione:printer',
    'emojione:camera',
    'emojione:video-camera',
    'emojione:microphone',
    'emojione:headphone',
    'emojione:magnifying-glass-tilted-left',
    'emojione:key',
    'emojione:wrench',
    'emojione:hammer-and-wrench',
    'emojione:nut-and-bolt',
    'emojione:chart-increasing',
    'emojione:chart-decreasing',
    'emojione:spiral-notepad',
    'emojione:scroll',
    'emojione:books',
    'emojione:open-book',
    'emojione:graduation-cap',
    'emojione:briefcase',
    'emojione:satellite-antenna',
    'emojione:satellite',
    'emojione:airplane',
    'emojione:rocket',
    'emojione:hourglass-with-flowing-sand',
    'emojione:stopwatch',
    'emojione:crystal-ball',
    'emojione:light-bulb',
    'emojione:battery',
    'emojione:telescope',
    'emojione:microscope',
];

export function searchIcons(query: string): string[] {
    return selectedIcons.filter(name =>
        name.toLowerCase().includes(query.toLowerCase())
    );
}

export function getIcon(name: string): string | null {
    return selectedIcons.includes(name) ? name : null;
}